### ISSUE TITLE
I dont know -> child_process.js:1230       throw errnoException(err, 'kill');

### ISSUE THREAD

**Issue by Theenoro** [WebReflection/dblite#43]
This is my errorcode
child_process.js:1230
      throw errnoException(err, 'kill');
            ^
   Error: kill EINVAL
    at exports._errnoException (util.js:746:11)
    at ChildProcess.kill (child_process.js:1230:13)
    at setUpAndGo (C:\Users\Theenoro\desk\Project Mio\app\node_modules\dblite\bu
ild\dblite.node.js:161:19)
    at Socket.onerror (C:\Users\Theenoro\desk\Project Mio\app\node_modules\dblit
e\build\dblite.node.js:135:11)
    at Socket.emit (events.js:107:17)
    at onwriteError (_stream_writable.js:317:10)
    at onwrite (_stream_writable.js:335:5)
    at WritableState.onwrite (_stream_writable.js:105:5)
    at fireErrorCallbacks (net.js:448:13)
    at Socket._destroy (net.js:486:3)

and this is the only thing I have written.
var dblite = require('dblite'),
    db = dblite('./db.sqlite');

**Comment by WebReflection** [comment]
most likely you have to setup where is your executable. 
https://github.com/WebReflection/dblite#bootstrap

**Comment by Theenoro** [comment]
sry i didn't wrote how i've solved my problem.  

I used an older version of node js. I didn't realised it.
